# Session 2: Matrix Operations & Linear Systems in Python

## Matrix Creation and Basic Operations

In [1]:
import numpy as np
# Creating matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Matrix A:\n", A)
print("Matrix B:\n", B)
# Matrix addition
print("A + B:\n", A + B)
# Matrix subtraction
print("A - B:\n", A - B)
# Scalar multiplication
print("2 * A:\n", 2 * A)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
A + B:
 [[ 6  8]
 [10 12]]
A - B:
 [[-4 -4]
 [-4 -4]]
2 * A:
 [[2 4]
 [6 8]]


![Basic_Operations_1](Basic_Operations_1.png)

In [9]:
A = np.array([[2,3],
              [1,5]])
B = np.array([[4, -1],
              [0, 2]])
print("A + B =\n",A + B)

C = np.array([[7, 6],
              [3, 2]])
D = np.array([[1, 4],
              [0, 5]])
print("C - D =\n", C - D)

E = np.array([[-2, 0],
              [1, 3]])
print("5E =\n", 5*E)

G = np.array([[0, 2],
              [-1, 3]])
H = np.array([[4, -2],
              [5, 1]])
I = np.array([[-3, 1],
              [0, 6]])
print("2(G+H)-3I =\n", 2*(G+H) - 3*I)

A + B =
 [[6 2]
 [1 7]]
C - D =
 [[ 6  2]
 [ 3 -3]]
5E =
 [[-10   0]
 [  5  15]]
2(G+H)-3I =
 [[ 17  -3]
 [  8 -10]]


In [12]:
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[5, 6], [7, 8]])
# Matrix multiplication using @ operator
print("A @ B:\n", A @ B)

# Element-wise multiplication using * operator
print("A * B (element-wise):\n", A * B)

A @ B:
 [[19 22]
 [43 50]]
A * B (element-wise):
 [[ 5 12]
 [21 32]]


![Basic_Operations_2](Basic_Operations_2.png)

In [11]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])
print("AB =\n", A@B)

A = np.array([[1, 0, 2],
              [-1, 3, 1]])
B = np.array([[3, 1],
              [2, 1],
              [1, 0]])
print("AB =\n", A@B)

AB =
 [[19 22]
 [43 50]]
AB =
 [[5 1]
 [4 2]]


In [9]:
# A = np.array([[1, 2], [3, 4]])
# B = np.array([[5, 6], [7, 8]])
# Transpose using .T
print("Transpose of A (A.T):\n", A.T)

# Transpose using np.transpose()
print("Transpose of B (np.transpose):\n", np.transpose(B))

Transpose of A (A.T):
 [[1 3]
 [2 4]]
Transpose of B (np.transpose):
 [[1 1]
 [2 2]]


![Basic_Operations_3](Basic_Operations_3.png)

## Advanced Matrix Operations

In [2]:
# Determinant
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)

# Checking invertibility
print("Is A invertible?", "Yes" if det_A != 0 else "No")

Determinant of A: -2.0000000000000004
Is A invertible? Yes


In [3]:
# Matrix inverse
if det_A != 0:
    inv_A = np.linalg.inv(A)
    print("Inverse of A:\n", inv_A)
else:
    print("Matrix A is not invertible")

Inverse of A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


![Advanced_Operations_1](Advanced_Operations_1.png)

![Advanced_Operations_2](Advanced_Operations_2.png)

In [13]:
# Identity matrix
I_2 = np.identity(2)
print("2x2 Identity matrix using np.identity():\n", I_2)

I_3 = np.identity(3)
print("3x3 Identity matrix using np.identity():\n", I_3)

2x2 Identity matrix using np.identity():
 [[1. 0.]
 [0. 1.]]
3x3 Identity matrix using np.identity():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
print(np.eye(3)) # A 3x3 Identity matrix

print(np.eye(3, 4, k=1)) # A 3x4 matrix with ones on the diagonal above the main diagonal.
print(np.eye(3, 4, k=2)) 
print(np.eye(3, 4, k=-1)) # A 3x4 matrix with ones on the diagonal below the main diagonal.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## Solving Linear Systems

In [5]:
# Solving Ax = b using np.linalg.solve()
A = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
x = np.linalg.solve(A, b)
print("Solution x to Ax = b using np.linalg.solve():", x)

Solution x to Ax = b using np.linalg.solve(): [-4.   4.5]


In [6]:
# Solving using matrix inverse: x = A^(-1) * b
A_inverse = np.linalg.inv(A)
inv_method_x = A_inverse @ b
print("Solution x using inverse method:", inv_method_x)

Solution x using inverse method: [-4.   4.5]


| Method                  | Recommendation    | Advantages                                                  | Disadvantages                                                         |
| ----------------------- | ----------------- | ----------------------------------------------------------- | --------------------------------------------------------------------- |
| `np.linalg.solve(A, b)` | ✅ **Recommended** | Efficient, numerically stable, directly solves the equation | Can only be used to solve equations, does not give the inverse matrix |
| `np.linalg.inv(A) @ b`  | ❌ Not recommended | Intuitive, gives the inverse matrix explicitly              | Slower, prone to numerical errors                                     |


#### Tips:  
If your goal is just to solve Ax=b, always use np.linalg.solve() first.  
Only use np.linalg.inv() when you actually need the inverse matrix itself.

![Advanced_Operations_3](Advanced_Operations_3.png)